package lab2;

/*
		 
CRIAR_TAREFA QUARTO 3
CADASTRAR_TAREFA QUARTO 0 10
CADASTRAR_TAREFA QUARTO 1 30 que_tarefa_longa
CRIAR_TAREFA COZINHA 2
CADASTRAR_TAREFA QUARTO 2 20
CADASTRAR_TAREFA COZINHA 0 30
CADASTRAR_TAREFA COZINHA 1 50
DESCRICAO_TAREFA QUARTO 1
DESCRICAO_TAREFA COZINHA 0
MEDIA_TAREFA QUARTO
MEDIA_TAREFA COZINHA
TAREFA_COMPLETA QUARTO
	 
		 
		 
CADASTRAR_LAZER TV
CADASTRAR_LAZER LIVRO 150
CADASTRAR_ATIVIDADE TV RUPAL 60
CADASTRAR_ATIVIDADE LIVRO HARRY_POTTER 50
CADASTRAR_ATIVIDADE TV GAMA 20
CADASTRAR_ATIVIDADE LIVRO SENHOR_DOS_ANEIS 70
TOTAL_ATIVIDADES TV
TOTAL_ATIVIDADES LIVRO
TEMPO_TOTAL TV
TEMPO_TOTAL LIVRO
MENOR_ATIVIDADE TV
MAIOR_ATIVIDADE LIVRO
ATIVIDADE_COMPLETA TV 
ATIVIDADE_COMPLETA LIVRO

CRIAR_ESTUDO PROGRAMACAO
ADICIONAR_MINUTOS PROGRAMACAO 100
CRIAR_ESTUDO_DIRIGIDO P2
CADASTRAR_ESTUDO_DIRIGIDO P2 PROGRAMACAO
TEMPO_TOTAL_DIRIGIDO P2
CRIAR_ESTUDO ARRAYS
ADICIONAR_MINUTOS ARRAYS 10
CRIAR_ESTUDO LISTA
ADICIONAR_MINUTOS LISTA 15
CRIAR_ESTUDO INT
ADICIONAR_MINUTOS INT 20
CADASTRAR_ESTUDO_DIRIGIDO P2 ARRAYS
CRIAR_ESTUDO FLOAT
ADICIONAR_MINUTOS FLOAT 30
CRIAR_ESTUDO STRING
ADICIONAR_MINUTOS STRING 40
CADASTRAR_ESTUDO_DIRIGIDO P2 LISTA
CRIAR_ESTUDO MAMMA_MIA
ADICIONAR_MINUTOS MAMMA_MIA 50
CADASTRAR_ESTUDO_DIRIGIDO P2 INT
CADASTRAR_ESTUDO_DIRIGIDO P2 FLOAT
CADASTRAR_ESTUDO_DIRIGIDO P2 STRING
ESTUDO_DIRIGIDO_COMPLETO P2 MAMMA_MIA
DIRIGIDO_COMPLETO P2
CRIAR_ESTUDO_DIRIGIDO PORT
CADASTRAR_ESTUDO_DIRIGIDO PORT MAMMA_MIA
DIRIGIDO_COMPLETO PORT
DIRIGIDO_TEMPO_TOTAL P2


*/